#!/usr/bin/env bash
#
# Cloudbox console
#
# This command will open an interactive console and enable you to execute all
# cloudbox command directly.

# Add support for ssh command `ssh user@host command`
if [ "$1" = "-c" ]; then
    cloudbox-$2
    echo ""
fi

clear
echo "Welcome to the cloudbox console"
echo "Enter 'help' to list available commands"
while true; do
    echo -ne "\r" && read -e -p "> " command
    if [[ "$command" == cloudbox* ]]; then
        command=${command#cloudbox}
    fi
    if [ "$command" == "exit" ]; then
        break
    elif [ "$command" == "" ]; then
        continue
    fi
    cloudbox $command
done

