#!/usr/bin/env bash
#
# Cloudbox console
#
# This command will open an interactive console and enable you to execute all 
# cloudbox command directly.

# Add support for ssh command `ssh user@host command`
if [ "$1" = "-c" ]; then
    cloudbox-$2
    echo ""
fi

echo "Welcome to the cloudbox console"
echo "Enter 'help' to list available commands"
while true; do
    read -p "> " command
    if [ "$command" = "exit" ]; then
        break;
    elif [ "$command" = "" ]; then
        continue;
    fi
    cloudbox-${command}
done

